export {
    IconLockBold,
    IconUserBold,
    IconSignOut,
    IconTable,
    IconMarkerCircle,
    IconStar,
    IconStarFill,
    IconBookmarkSimple,
    IconFilePlus,
    IconPlusBold,
    IconTrashBold,
    IconEyeBold,
    IconHeartBold,
    IconHeartFill,
} from "@iconify-prerendered/vue-ph";
